#define VGA_WIDTH 80
#define VGA_HEIGHT 25
#define VGA_MEMORY ((unsigned short*)0xB8000)
#define OS_VERSION "v0.2"

typedef enum {
    COLOR_BLACK=0,COLOR_BLUE,COLOR_GREEN,COLOR_CYAN,
    COLOR_RED,COLOR_MAGENTA,COLOR_BROWN,COLOR_GRAY,
    COLOR_DARK_GRAY,COLOR_BRIGHT_BLUE,COLOR_BRIGHT_GREEN,
    COLOR_BRIGHT_CYAN,COLOR_BRIGHT_RED,COLOR_PINK,
    COLOR_YELLOW,COLOR_WHITE
} vga_color;
